[package]
name = "macron-map"
description = "The key-value collection parser"
keywords = ["macros", "macro", "proc", "declarative"]
categories = ["development-tools", "rust-patterns"]
version = "0.1.2"
license = "MIT"
authors = ["Bulat Sh. <synapdrake@ya.ru>"]
repository = "https://github.com/fuderis/macron-rs/tree/main/crates/map"
readme = "README.md"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
