[package]
name = "macron-impl-error"
description = "The implementation of trait Error"
keywords = ["macros", "macro", "proc", "derive"]
categories = ["development-tools", "rust-patterns"]
version = "0.1.3"
license = "MIT"
authors = ["Bulat Sh. <synapdrake@ya.ru>"]
repository = "https://github.com/fuderis/macron-rs/tree/main/crates/impl-error"
readme = "README.md"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
